name: Cities Vision
favicon: null
layout_spectrum: 0.508492091903463
typography_spectrum: 0.020141369430348277
title: Cities Vision
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.01786641636863351
  lightness: 0.8912352621555328
  saturation: 0.7031843378208578
  rhythmicContrast: 0.41428002854809165
purpose: []
